fr24feed-piaware:
  restart: unless-stopped
  build: "fr24feed-piaware"
  # expose
  # 30001 - Raw output listen port
  # 30002 - Feed Dump1090 input listen port
  # 30003 - TCP BaseStation output listen port
  # 30004 - TCP Beast input listen port
  # 30005 - TCP Beast output listen port
  # 8754 - DUMP1090 server port
  # 8080 - HTTP server port
  expose:
    - "30001"
    - "30002"
    - "30003"
    - "30004"
    - "30005"
    - "30104"
    - "8754"
    - "8080"
  devices:
    - "/dev/bus/usb"
  # ports
  # 8754 - DUMP1090 server port
  # 8080 - HTTP server port
  ports:
    - "8754:8754"
    - "8080:8080"
  logging:
    options:
      max-size: "30m"
